# Thanks to https://github.com/starkat99/appveyor-rust

os: Visual Studio 2017
platform: Any CPU

clone_depth: 1
clone_folder: C:\projects\tox

branches:
  except:
    - /test.*/

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
  # env variables for debugging
  RUST_BACKTRACE: "1"

install:
  - cd C:\projects\tox
  # install rustc & cargo
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
